### ISSUE TITLE
Undefined Array Key "Data" on User Create 

### ISSUE THREAD

**Issue by mous13** [forumify/forumify-platform#32]
Error happens in the admin cp

**Comment by jannes-io** [comment]
Hi @mous13,

Thanks for the contribution, but as discussed on Discord, there's a bit more to this story than it seems.

This is actually an oversight from refactoring over to the `AbstractCrudController`. When a user is created it should use the `RegisterType` to ensure username, email, password,... meet the (current and future) constraints set on all users. Additionally, the create user service should be used to ensure a verification email is sent, and, if any other "new user" actions need to be added in the future, they can be added centrally.

The short term fix for this would be to set the protected property `allowCreate` to false, to disable user creation from the admin panel again.

Long term, if we want admins to be able to create users, we should plug it into the existing new user flow that is also used in the installation form, the create user command, and, ofcourse, the registration form.

You can submit a PR with either of these options if you're interested in following up.

**Comment by jannes-io** [comment]
@mous13 I've disabled creating users from the admin panel.
