### ISSUE TITLE
Dark mode in Admin settings & screen flicker

### ISSUE THREAD

**Issue by B1FoxTopic** [forumify/forumify-platform#42]
I'm not sure if this feature already exists, but it would be great to have the option to enable Dark Mode for the admin side of your Forumify website. 👍 

Secondly, there seems to be a potential issue or bug: when navigating through different pages, the webpage briefly turns black for a second before returning to white. This can be quite harsh on the eyes. :)

GIF: https://imgur.com/ndxl1Gp

**Comment by jannes-io** [comment]
Will be added in next release
