### ISSUE TITLE
Email Outgoing Configuration

### ISSUE THREAD

**Issue by mous13** [forumify/forumify-platform#46]
Add the ability for admins to configure what emails are sent to their users.

ie: disable new private message email.

**Comment by jannes-io** [comment]
@mous13 users can configure this themselves in settings > notification settings.

We will probably not make this a global setting. If you are using self hosting, you can decorate the `MessageReplyNotificationType` service and just do nothing for function `handleNotification`.

[Service Decoration](https://symfony.com/doc/current/service_container/service_decoration.html)
[Other ways to override services](https://symfony.com/doc/current/bundles/override.html#services-configuration)
