### ISSUE TITLE
have the record name display in award section

### ISSUE THREAD

**Issue by Crazyz24** [forumify/forumify-platform#47]
![d1f27658bda0078a90a895093692e7a9](https://github.com/user-attachments/assets/556c0cab-7c03-42d1-99ae-a402b351bcec)
![c12f48893c58bba4d0c81d2912f43499](https://github.com/user-attachments/assets/144d340e-0e6a-4e13-9ac6-ca3599635e93)

Instead of the generic text saying Record document is it possible to make it display the name of the actual record selected?

**Comment by jannes-io** [comment]
Moved to the correct repository
