### ISSUE TITLE
Donation Plugin - Addon feature

### ISSUE THREAD

**Issue by JLAFLASH27** [forumify/forumify-platform#48]
Would love to have the Donation plugin upgrade so that when a donation comes in, it will automatically send the following: 

1. Private Message the individual a customizable thank you message for their donation. 
2. Post a message of their donation in a selected forum thread.  

Thanks

**Comment by jannes-io** [comment]
Thanks for the suggestion, definitely something we want to add.

I'm going to move this to the correct repository so we can follow it there https://github.com/forumify/forumify-donations-plugin/issues/5
