### ISSUE TITLE
Ability to add a user to a PM

### ISSUE THREAD

**Issue by JLAFLASH27** [forumify/forumify-platform#49]
Ability to add a user to a PM that was already posted.  

IE:  member missed adding in a leader prior to sending message and now would have to start a whole new PM to add them.
![image](https://github.com/user-attachments/assets/f9627bbb-1d10-4c7d-9781-03a66bd7fcb2)

**Comment by Crazyz24** [comment]
Also the ability to remove people from messages!

**Comment by jannes-io** [comment]
done & done 🙂 

will be added in the next release.
