### ISSUE TITLE
1305 Savepoint doesn't exist on fresh install.

### ISSUE THREAD

**Issue by mous13** [forumify/forumify-platform#5]
On a fresh install, when you get to the stage of creating an admin account, it throws the following error.

`An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT DO
  CTRINE_14 does not exist`
  
  The account is created but admin privileges aren't assigned. Running `symfony console forumify:platform:create-user --admin` works without any issues.
  
  Replication:
  `symfony console doctrine:database:drop`
  `forumify:platform:install`

**Comment by jannes-io** [comment]
I think this only applies to development environments as I don't see anyone dropping their database on a live environment. So if there's a good-enough workaround we're not going to investigate this further.
