### ISSUE TITLE
Forum post feature request.

### ISSUE THREAD

**Issue by Crazyz24** [forumify/forumify-platform#7]
General forum post management features:
- Locking/Unlocking
- Pinning
- Moving
- Hiding specific posts from people without permission
- Scheduling a post for a different date

**Comment by jannes-io** [comment]
Completed:

- Locking/Unlocking
- Pinning
- Moving
- Hiding specific posts from people without permission

**Comment by jannes-io** [comment]
Going to close this, as we probably won't take on board scheduling posts for a specific date/time in the core feature set.
